const main = () => console.error(1)